### ISSUE TITLE
air sdk 33.0.0.212 packaged app(64bit ANE) crashes on android device

### ISSUE THREAD

**Issue by ReginaSun** [distriqt/ANE-Core#10]
I found the log that caused the crash as follows(air.tw.com.xxxx.xxxx is us app package name)

08-05 15:55:50.862  2773  4430 I ActivityManager: Start proc 30059:air.tw.com.xxxx.xxxx/u0a352 for activity air.tw.com.xxxx.xxxx/.AppEntry
08-05 15:55:50.957  2773  4430 W ActivityManager: Slow operation: 51ms so far, now at attachApplicationLocked: after mServices.attachApplicationLocked
08-05 15:55:51.478  2773  4430 I ActivityManager: Config changes=480 {1.0 466mcc89mnc [zh_TW_#Hant] ldltr sw360dp w592dp h336dp 480dpi nrml land finger -keyb/v/h -nav/h appBounds=Rect(0, 0 - 1776, 1080) s.55}
08-05 15:55:51.637  2773  4430 I ActivityManager: Override config changes=480 {1.0 466mcc89mnc [zh_TW_#Hant] ldltr sw360dp w592dp h336dp 480dpi nrml land finger -keyb/v/h -nav/h appBounds=Rect(0, 0 - 1776, 1080) s.55} for displayId=0
08-05 15:55:51.763 30059 30059 E AndroidRuntime: FATAL EXCEPTION: main
08-05 15:55:51.763 30059 30059 E AndroidRuntime: Process: air.tw.com.xxxx.xxxx, PID: 30059
08-05 15:55:51.763 30059 30059 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lair/tw/com/bonuswinner/bwmj16tw/AppEntry$LicenceServiceAsyncTask;
08-05 15:55:51.763 30059 30059 E AndroidRuntime:        at air.tw.com.xxxx.xxxx.AppEntry.initLicenceService(AppEntry.java:305)
08-05 15:55:51.763 30059 30059 E AndroidRuntime:        at air.tw.com.xxxx.xxxx.AppEntry.onCreate(AppEntry.java:290)
08-05 15:55:51.763 30059 30059 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6975)
08-05 15:55:51.763 30059 30059 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
08-05 15:55:51.763 30059 30059 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2775)
08-05 15:55:51.763 30059 30059 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2897)
08-05 15:55:51.763 30059 30059 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(Unknown Source:0)
08-05 15:55:51.763 30059 30059 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1598)
08-05 15:55:51.763 30059 30059 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:105)
08-05 15:55:51.763 30059 30059 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:251)
08-05 15:55:51.763 30059 30059 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6572)
08-05 15:55:51.763 30059 30059 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-05 15:55:51.763 30059 30059 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
08-05 15:55:51.763 30059 30059 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
08-05 15:55:51.763 30059 30059 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "air.tw.com.xxxx.xxxx.AppEntry$LicenceServiceAsyncTask" on path: DexPathList[[zip file "/data/app/air.tw.com.xxxx.xxxx-GLPb2Ku5ftkMyFhzHPF_nw==/base.apk"],nativeLibraryDirectories=[/data/app/air.tw.com.xxxx.xxxx-GLPb2Ku5ftkMyFhzHPF_nw==/lib/arm64, /data/app/air.tw.com.xxxx.xxxx-GLPb2Ku5ftkMyFhzHPF_nw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
08-05 15:55:51.763 30059 30059 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
08-05 15:55:51.763 30059 30059 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
08-05 15:55:51.763 30059 30059 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
08-05 15:55:51.763 30059 30059 E AndroidRuntime:        ... 14 more
08-05 15:55:51.770  2773  3669 D ActivityManager: New dropbox entry: air.tw.com.xxxx.xxxx, data_app_crash, a228c9b4-9a10-4fc4-a6ab-58e27a6ecb97
08-05 15:55:51.781  2773  3669 W ActivityManager:   Force finishing activity air.tw.com.xxxx.xxxx/.AppEntry
08-05 15:55:51.850  2773  2856 I ActivityManager: Showing crash dialog for package air.tw.com.xxxx.xxxx u0
08-05 15:55:52.334  2773  2854 W ActivityManager: Activity pause timeout for ActivityRecord{4f0f21d u0 air.tw.com.xxxx.xxxx/.AppEntry t159 f}

On August 1st I received a new air sdk(33.0.0.212) from Harman, which crashed when I packaged the app and started it on the android device.

If I don't use any ANE, it works fine.

Harman’s letter indicates that the previous version of the air sdk will be discontinued at the end of July. I wonder if it is related.

Can you help me with this issue?

Thanks.

**Comment by marchbold** [comment]
Hi,

We aren't seeing this issue with any of our ANEs and 33.0.0.212. I suggest you isolate the ANE causing the issue and if it's one of ours post an issue in that repository.

**Comment by ReginaSun** [comment]
OK, Thanks.

**Comment by marchbold** [comment]
Harman have informed me that have found the issue here and will update in the next build.

**Comment by ReginaSun** [comment]
I tried to do some experiments and had the following two findings.

1.The app crashes when I use the facebook api ANE(v6.0.165 beta) with the AIR SDK(33.0.212 beta).
  
  Works fine with the latest facebook api ANE(v6.0.168).


2.App crashes when I only package com.distriqt.firebase.Database.ane in the Firebase ANE(v3.0.001 beta) but not initialized.


Update facebook api ANE(v6.0.168) and remove <extensionID>com.distriqt.firebase.Database</extensionID>, the app is working fine.


Thank you for your suggestion and support.
