### ISSUE TITLE
myflashlabs firebase Ane conflicts

### ISSUE THREAD

**Issue by scionGbh** [distriqt/ANE-Core#12]
Hi there, I am using your Media Player ane along with myflashlabs firebase anes.

After the final update It came with this error

dx tool failed:
UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Lcom/adobe/air/ActivityResultCallback;

Previously I had no problems using your core.noair.ane but today even using your latest
core.noair.ane I am having this issue.

I am stuck here cause I can not remove OverrideAir.ane from myflashlabs.com as the latest version needs it.

The core.noair.ane should have no other functions than needed to register the api.

can you help me please?

**Comment by marchbold** [comment]
Do you have the Core ANE in your extension directory still? 

You must make sure that you only have the noair version in your extension dir, even if you haven't added it to your project you must make sure the normal version is not available during packaging as it can be included unintentionally in your build.

**Comment by scionGbh** [comment]
Hi there, sorry, my bad, the issue was exactly that, I did not notice because I update all anes but one of the ane path was reflecting the old directory, so as you said, the compiler was loading all anes twice.

thanks

**Comment by marchbold** [comment]
No problem. Glad it was a simple fix.
