### ISSUE TITLE
Core.init kills the invoke event from another ANE on iOS

### ISSUE THREAD

**Issue by pis0** [distriqt/ANE-Core#13]
.. and it doesn't matter the initialization order.. and I'm also a little bit confused 'cause if I just embed the Core ANE, without call the init method, all the stuff seems to be working fine, the invoke event from the other ANE as well... 

distriqt ANEs I use in the app:

com.distriqt.NetworkInfo
com.distriqt.Share
com.distriqt.Vibration
com.distriqt.Dialog
com.distriqt.Notifications
com.distriqt.ApplicationRater

how to proceed? :)

**Comment by pis0** [comment]
@marchbold  interesting.. how can I access the code?

**Comment by marchbold** [comment]
It's in this repository:

https://github.com/distriqt/ANE-Core/tree/master/integration
