### ISSUE TITLE
Error building for IOS: implementation of 'com.distriqt.Core' not found

### ISSUE THREAD

**Issue by doogog** [distriqt/ANE-Core#14]
I'm on PC trying to build for iOS and it's giving me the error: An implementation for native extension 'com.distriqt.Core' required by the application was not found for the target platform.

I'm using the latest Core ANE downloaded from github.

I'm using ADT command line. If I remove the -platformsdk option, I get the ld64 missing functions error, so I followed the docs and tried linking against 11.0.modified, which gives me the above error. I've also tried linking against iOS 12.1 SDK, but that gives me the same error.

Any idea what I should try next?

**Comment by SpikeApp** [comment]
If you need support on how to use Spike or solve a specific issue please join our support group at https://www.facebook.com/groups/spikeapp/

We do NOT give one on one support by e-mail.

Thank you!

The Spike Team

**Comment by marchbold** [comment]
Sounds like you aren't packaging the ANE correctly or specifying the wrong platform.

**Comment by doogog** [comment]
I'm using the command line with:

adt.bat ^
-package ^
-target ipa-ad-hoc ^
-useLegacyAOT no ^
-storetype pkcs12 ^
-storepass xxx ^
-keystore ../../certs/ios/xxx.p12 -provisioning-profile ../../certs/ios/xxx.mobileprovision ^
MyApp.ipa ^
MyApp-app.xml ^
Assets.car ^
MyApp.swf ^
data ^
assets ^
icons ^
-extdir ../src/ane ^
-extdir ../src/ane_ios ^
-platformsdk ../src/platformsdk/iPhoneOS11.0.sdk

The ANE is located in the mentioned folder. The inclusion of the platformsdk option seems to be hanging it up. Am I missing anything here?

**Comment by marchbold** [comment]
Looks like you have 2 `extdir` options, you can only have one as far as I know.

**Comment by doogog** [comment]
I see, let me attempt to merge them.

**Comment by doogog** [comment]
I've reduced it to 1 extdir option, but the issue persists. What can I try next? I'm using AIR SDK 32.

**Comment by marchbold** [comment]
Are you sure all your ANEs are in the one directory ?

**Comment by doogog** [comment]
Yup, they are indeed in the same directory.

**Comment by marchbold** [comment]
Not really sure what else to suggest, the error indicates that the Core ANE cannot be found in the specified extdir. Please double check it is in there

**Comment by doogog** [comment]
I should be using the Core found here : https://github.com/distriqt/ANE-Core/blob/master/lib/com.distriqt.Core.ane

right?

**Comment by marchbold** [comment]
Yes that is the correct link to the latest release.

This ANE doesn't need the iOS SDK.

What other ANEs are you using? Some of them require the iOS SDK. 

You shouldn't need to modify the SDK for any of our ANEs, however you occasionally need to modify the AIR SDK.

**Comment by doogog** [comment]
I'm using InAppBilling as well and GameServices.

**Comment by marchbold** [comment]
InAppBilling requires a version of the iOS SDK, I'd suggest using the more recent 12.4
