### ISSUE TITLE
The content cannot be loaded because there was a problem loading an extension: Error: Duplicate platform Android-ARM found for extension com.distriqt.Core

### ISSUE THREAD

**Issue by idzdigital** [distriqt/ANE-Core#16]
I have added Core, Firebase and InAppBilling in my project. While compiling it I get the above error. If I remove Core and compile then it works perfectly fine on PC.

**Comment by marchbold** [comment]
Are you sure you have the latest build of the ANE? You don't have two versions of the ANE in your path somewhere?

**Comment by idzdigital** [comment]
Yes I have the latest build. I am using com.distriqt.Core.noair

**Comment by marchbold** [comment]
What IDE are you using? Could be a cached version of the ANE somewhere on your machine?

**Comment by idzdigital** [comment]
I am using Adobe Animate.

**Comment by marchbold** [comment]
I'm not exactly sure with Animate, but a normal file search of your system should find any versions.

**Comment by idzdigital** [comment]
I just searched my project folder and I did not find any other version of that ane.

**Comment by marchbold** [comment]
It could be in an application cache folder

**Comment by marchbold** [comment]
eg `C:\Users\username\AppData\Local\Temp`

**Comment by idzdigital** [comment]
Yes cleaning the cache worked. Thanks a lot for your help.

**Comment by marchbold** [comment]
👍

**Comment by marchbold** [comment]
Just for our information, which folder did you find it in?

**Comment by idzdigital** [comment]
C:\Users\username\AppData\Local\Temp
