### ISSUE TITLE
After update to the HARMAN AIR SDK BETA - [Fault] exception, information=Error: The native extension context could not be created

### ISSUE THREAD

**Issue by Faketa** [distriqt/ANE-Core#17]
After update to the latest HARMAN AIR SDK I've just started to get below listed error within my ANEs:
```
[Fault] exception, information=Error: The native extension context could not be created
```

**Comment by marchbold** [comment]
Can you include the logs from the device and exactly which version of the SDK you are using?

The beta is still in development and has several issues so you probably should report them to harman, but we will investigate if you can give us some more information to replicate the error.
