### ISSUE TITLE
ld: library not found for -lclang_rt.ios

### ISSUE THREAD

**Issue by ChacHauLam** [distriqt/ANE-Core#20]
Hi,

I upgraded an app to Air SDK 33.1.1.217. I also updated all the distriqt ANE's I am using to their most recent versions. I only use distriqt ANEs.

Building to Android works fine. When I build to iOS I get an error. I removed all ANEs other than ANE-Core and still get the error, so think the issue may be related to ANE-Core?

The Error I get is:
![Capture](https://user-images.githubusercontent.com/14804172/92000032-f7d16900-ed34-11ea-81bd-97071be48102.JPG)

**Comment by SpikeApp** [comment]
If you need support on how to use Spike or solve a specific issue please join our support group at https://www.facebook.com/groups/spikeapp/

We do NOT give one on one support by e-mail.

Thank you!

The Spike Team

**Comment by ChacHauLam** [comment]
That worked! Thank you!
