### ISSUE TITLE
A tool for atomically connecting libraries to a project [Feature]

### ISSUE THREAD

**Issue by OneHalf3544c** [distriqt/ANE-Core#21]
Hi. Sorry I do not know where it would be better to place this topic.

I use a lot of your libraries.I don't update them very often. But each time I have to look through the descriptions for each one and there is a high probability that something is not understood or missed. I write for myself a tool that would help me do everything faster and more accurately. It can make a list of libraries and a description of the application. Maybe you already have something like this? I also want to automate uploading the necessary libraries to the project, but I haven't figured out how to do it yet. Perhaps you will be interested in this development or you can help me solve some issues and I will share it with everyone.
[DistriqtConf.zip](https://github.com/distriqt/ANE-Core/files/5177521/DistriqtConf.zip)
![2020-09-04_20-44-13](https://user-images.githubusercontent.com/5443735/92297347-1d35c100-ef47-11ea-9467-76b8771696f2.png)
![2020-09-05_6-52-30](https://user-images.githubusercontent.com/5443735/92297348-1e66ee00-ef47-11ea-801a-85bdd3caf63d.png)

**Comment by marchbold** [comment]
Totally understand that updating the ANEs is a painful process. We have been thinking about this for quite some time and can see our current proposal here:

https://forum.starling-framework.org/d/22650-air-package-manager

Please consider having a look at our proposed `apm` and providing any feedback there

https://github.com/airnativeextensions/apm

**Comment by OneHalf3544c** [comment]
Ok, 
I did not understand whether there is a utility or not, I made for several of your packages, it is quite working, but under Windows OS
I will continue to develop it to automate work with my projects.

[DistriqtConf.zip](https://github.com/distriqt/ANE-Core/files/5179255/DistriqtConf.zip)
.

**Comment by marchbold** [comment]
No there is no utility as yet, this is a proposal to do something like your app but more general. Appreciate you sharing your app it looks like a great little utility.

**Comment by marchbold** [comment]
apm has been released and is fully functional now. 

https://github.com/airsdk/apm
