### ISSUE TITLE
Verification Fails or Does Not Compile!

### ISSUE THREAD

**Issue by Mighat** [distriqt/ANE-Core#25]
**Common Specs:**
Windows 7 Ultimate Service Pack 1 64-bit
iPhone 6s ios 14.2
iPad 2 ios 9.3.5
ANE MediaPlayer 4.3.010
ANE Share 6.0.062
-----------------------------------------
**Test 1**
SDK 33.1.1.406
ANE Core 6.3.022
<application xmlns="http://ns.adobe.com/air/application/32.0" minimumPatchLevel="0">

D:\sdk33.1.1.406\bin\adt -package -target ipa-test -useLegacyAOT yes -provisioning-profile qh_dev.mobileprovision -storetype pkcs12 -keystore win_dev.p12 -storepass XXXXXX QH7.4_Dev_1.ipa QuranHakim_1.xml QH.swf icn_ios dta -extdir ane Default~iphone.png Default-375w-667h@2x~iphone.png Default-414w-736h@3x~iphone.png Default-568h@2x~iphone.png Default-812h@3x~iphone.png Default-Portrait@2x.png Default-Portrait@2x~ipad.png Default-Portrait~ipad.png Default-Portrait-1112h@2x.png Default@2x~iphone.png Assets.car

Result:
Compiles, but does not install (Verification Failed).
Same result if I change "../application/33.1" to "../application/32.0"
BTW, No problem with Android if I use this same config.
![Screenshot_1](https://user-images.githubusercontent.com/65052935/110710584-fc2e8100-81b2-11eb-91ab-05509f38f069.png)

-------------------------------------
**Test 2**
SDK 33.1.1.385 ***
ANE Core 6.3.022
<application xmlns="http://ns.adobe.com/air/application/32.0" minimumPatchLevel="0"> ***

D:\sdk33.1.1.385\bin\adt -package -target ipa-test -useLegacyAOT yes -provisioning-profile qh_dev.mobileprovision -storetype pkcs12 -keystore win_dev.p12 -storepass XXXXXX QH7.4_Dev_2.ipa QuranHakim_2.xml QH.swf icn_ios dta -extdir ane Default~iphone.png Default-375w-667h@2x~iphone.png Default-414w-736h@3x~iphone.png Default-568h@2x~iphone.png Default-812h@3x~iphone.png Default-Portrait@2x.png Default-Portrait@2x~ipad.png Default-Portrait~ipad.png Default-Portrait-1112h@2x.png Default@2x~iphone.png Assets.car

Result:
Does not compile. with this error:
ld: library not found for -lclang_rt.ios
ld: library not found for -lclang_rt.ios
Compilation failed while executing : ld64

And if I use "33.1" instead of "32.0":
error 102: Invalid namespace http://ns.adobe.com/air/application/33.1

**Comment by SpikeApp** [comment]
If you need support on how to use Spike or solve a specific issue please join our support group at https://www.facebook.com/groups/spikeapp/

We do NOT give one on one support by e-mail.

Thank you!

The Spike Team

**Comment by marchbold** [comment]
There are issues with new certificates and signing in AIR 33.1.1.406.  

Check the discussion forum and issue tracker for details.

https://github.com/Gamua/Adobe-Runtime-Support/discussions/723

Also generally you shouldn't be using the legacy AOT.
