### ISSUE TITLE
Repackage ANEs with possible fix to run ANEs on macOS Big Sur iOS Simulator with latest Xcode?

### ISSUE THREAD

**Issue by derRaab** [distriqt/ANE-Core#26]
The last two month I spent updating a 6 year old AIR for mobile project. One of the many problems I had, after updating all libraries to ensure the latest iOS support, was, that I was never able to test / run the app within the latest iOS Simulator on my MacBook Pro with macOS Big Sur. And I wasn't the only one (found some on the web). Since I couldn't fix it I did only use on device testing. But 4 days ago the github user @buyANE found the possible answer: 

QUOTE from https://github.com/Gamua/Adobe-Runtime-Support/issues/569#issuecomment-797451639:

_@derRaab recent days i met your problem as well,and finally i found the problem and get it done, I found you use distriqt's ANE,It's the ANE's problem,with the latest macos,you can only build 64bit ipa,but distriqt's ANE have "-ios_version_min 9.0" in there ane's platform.xml file,this made the MinimumOSVersion drop to 9.0 even you set it to 11.0 in your app-app.xml file,when compile the error you post will show.
to get this prolblem done,you can ask them to repackage the ane for you. When repackage ane,remove -ios_version_min 9.0 or set it to -ios_version_min 11.0. After repackage just compile and build for simulator and everything is fine._

I would love to test if that would actually work, so it would be really helpful if i could test repackaged ANEs? I use 
- com.distriqt.Core
- com.distriqt.Dialog
- com.distriqt.Notifications
- com.distriqt.Application

but I have no clue which defines the said ios_version_min.

Is it possible for you to repackage these ANEs for me?

**Comment by marchbold** [comment]
I can repackage any of the ANEs that have a minimum iOS version of 9, some of them have higher requirements but I don't see any of these in your list.

**Comment by derRaab** [comment]
@marchbold Hi! Just to be clear: None of these 4 define define a minimum iOS version?

**Comment by marchbold** [comment]
Ah no, they all do.

**Comment by derRaab** [comment]
Ok. So then I'd love to try the repackaged versions. :)

**Comment by marchbold** [comment]
underway...

**Comment by derRaab** [comment]
@marchbold Great! I see you already did update ANE-Core. Please let me know when you're done and I'll try them. :)

**Comment by marchbold** [comment]
Okay, those 4 should be done now. Let me know if there are any others you need.

**Comment by derRaab** [comment]
@marchbold ❤️ - workes like a charm! Thank you! I think it might be a good idea to remove the minimum version from all ANEs. :)

**Comment by marchbold** [comment]
Yes, we will remove it from all the ANEs and leave it up to devs to manage the minimum version I suppose.
