### ISSUE TITLE
Iphone simulator issue with Apache Flex mobile

### ISSUE THREAD

**Issue by 42retfa** [distriqt/ANE-Core#28]
Hi,

I'm trying to test a flex mobile project on the iPhone simulator but I get the following error :

<img width="486" alt="Capture d’écran 2021-08-03 à 13 52 10" src="https://user-images.githubusercontent.com/2365180/128239740-098bdcda-2bbe-43bd-9056-793134102fda.png">

Environment :

- MacOS Big Sur
- Xcode is 12.5.1
- AIR 33.1.1.575

ANE (latest versions) included in the project :

- androidx.core.ane
- com.distriqt.Core.ane
- com.distriqt.Application.ane
- com.distriqt.Share.ane

This issue seems to be very similar to #26 

The Iphone Simulator is working properly when compiling a simple "blank" project without ANE.

Any Idea ?

Thanks in advance.

Vincent.

**Comment by SpikeApp** [comment]
If you need support on how to use Spike or solve a specific issue please join our support group at https://www.facebook.com/groups/spikeapp/

We do NOT give one on one support by e-mail.

Thank you!

The Spike Team

**Comment by marchbold** [comment]
Can you try with the latest releases we pushed today? There was a flag in the Share ANE that may have caused this issue.

**Comment by 42retfa** [comment]
Hi Michael,

Iphone simulator is launching with this new version of the Share extension, but it shutdown  right after the splash screen,
though it's not anymore related to the ANE because the same thing happened with a blank application. 
It must be something in the AIR 33.1.1.575 version because it doesn't crash with  AIR 33.1.1.444.

Has always, thank you for the quick answer.

Vincent.

**Comment by marchbold** [comment]
Great, glad to hear it was a simple fix. Hopefully Harman can resolve the other issue quickly for you.
