### ISSUE TITLE
Core.isSupported returns false on Windows 10

### ISSUE THREAD

**Issue by PippoApps** [distriqt/ANE-Core#29]
Hello there!
Launching AIR debug from Animate, AIR 33.1.1.575.
Windows 10 Pro 19042.1165.
Trying to use NativeWebView, but Core.isSupported returns false.

**Comment by marchbold** [comment]
You should be able to ignore the Core.isSupported flag. There is no real direct functionality in the extension so generally this flag isn't needed. I will look into it though. 

Is the NativeWebView.isSupported returning true?

**Comment by PippoApps** [comment]
Yep skipping the Core.isSupported part works fine.
Thx
