### ISSUE TITLE
ERROR ITMS-90034 Missing or invalid signature. The bundle com.distriqt.extensions.CoreNativExtension

### ISSUE THREAD

**Issue by railnation** [distriqt/ANE-Core#3]
Hi, 

I use the Core.ane with GameServices.ane. If I try to upload the IPA I get the following error. 

ERROR ITMS-90034: "Missing or invalid signature. The bundle 'com.distriqt.extensions.CoreNativeExtension' at bundle path 'Payload.....
CoreNativeExtension.framework is not signed using an Apple submission certificate.

**Comment by marchbold** [comment]
Hi,
Can you go through the advice from Apple to check your certificates?

https://developer.apple.com/library/ios/technotes/tn2318/_index.html#//apple_ref/doc/uid/DTS40013777-CH1-TNTAG1

**Comment by railnation** [comment]
We have an Enterprice Cert and a Itunes App Store Cert. Both are working before I use the Core.ane

**Comment by marchbold** [comment]
Okay, 
We'll look into it.

**Comment by railnation** [comment]
Do you need any other Information, like AIR SDK or something?

**Comment by marchbold** [comment]
Any information you can provide would be helpful, version of AIR and the iOS SDK you are using to start?

How are you uploading your application, are you using the latest version of the application loader?

**Comment by railnation** [comment]
I use the Adobe Air 17 SDK. IOS 4.3 SDK. Yes I use the lastet version of the application loader

**Comment by marchbold** [comment]
4.3? Can you please update to 8, our extensions aren't supported on 4.3.
Let me know how the update goes.
