### ISSUE TITLE
Error Creating Files 

### ISSUE THREAD

**Issue by NathanFitchett** [distriqt/ANE-Core#30]
Alright So I have been struggling to get this to work. I downloaded the Newest Version of Adobe SDK on Harman. I used APM and successfully downloaded and implemented all Files into Animate CC. I was struggling with my XML however after generating one using APM it works now. Here is the error I get now

![Error aapt tool](https://user-images.githubusercontent.com/6869776/157550024-74fffd4a-b3dc-417c-9666-3bf02e9fca9a.png)
 
Here is my XML how its being used : 

[Stack Cats-app.pdf](https://github.com/distriqt/ANE-Core/files/8218681/Stack.Cats-app.pdf)

Please if anyone can help me out I would greatly appreciate it! It's been 4hrs now haha.

**Comment by marchbold** [comment]
I'd recommend posting on the AIR forum rather than here:

https://github.com/airsdk/Adobe-Runtime-Support/discussions

**Comment by NathanFitchett** [comment]
Okay

**Comment by marchbold** [comment]
Just a quick guess from my side though, I'd say you are using our latest extensions with an old version of the Android build tools. Make sure you have updated Android Studio and the build tools in the sdk manager

**Comment by NathanFitchett** [comment]
Interesting I didn't even know I had Android Studio Installed. I will check on that if I can't figure it out Ill post on the link you provided thanks sir!

**Comment by marchbold** [comment]
Some info here: https://airsdk.dev/docs/basics/install/windows#android-setup

**Comment by NathanFitchett** [comment]
Okay. Is having Android Studio installed a new thing that you need for the Distriqt tools to work etc?

**Comment by marchbold** [comment]
No it's an AIR requirement. AIR has taken the approach of many of the other cross platform tools (Unity/Flutter etc) where the Android SDK is used directly. You don't need android studio, just the android sdk and build tools, but android studio is the easiest way to install and manage this currently.

**Comment by NathanFitchett** [comment]
Okay thank you for the information. Working on it now.

**Comment by NathanFitchett** [comment]
Well I downloaded Android Studio and the components. After That is there anything specific I need to do or is downloading it all that is needed?

**Comment by NathanFitchett** [comment]
I just installed the newest version of Java as well. Argh. I'm sure I am missing something more complicated...

**Comment by marchbold** [comment]
You need to have version 11 of Java currently I believe, and you need to specify the path to the android sdk in the adt.cfg.

honestly it's better if you ask the Harman support on the air forum directly. They are better suited to answering these sorts of questions and there is a whole community there.

**Comment by SporeProductions** [comment]
@NathanFitchett Did you ever solve this?
Here I am 2 years later, same error output you have. I can publish an Android APK targeting Android 33 just fine but as if I try to include Distriqt ANEs, the above happens. I already updated tools, JAVA_HOME etc to get the base project without ANEs to compile/package just fine. Using Air 50.2.3.8

Too many discussions I come across just say to use "new way" to build but I haven't found straightforward instructions on what should change. I thought I was using the new way since I can build to target Android 33 as long as I don't include Distriqt ANEs.

**Comment by NathanFitchett** [comment]
@SporeProductions Hey what's up man It definitely has been a while. I remember I did fix this. It's been so long though The only thing I could remember is that I think it was a district core ane that I was missing or didn't implement. I would have to go back in and double check. I was just going to start developing again so I have to look over everything anyways. Maybe you can upload your files on your profile And I can take a look and compare it to my last working build.

**Comment by marchbold** [comment]
I believe you need to ensure you have setup the android sdk and java paths correctly either in adt.cfg manually or via the air sdk manager.
