### ISSUE TITLE
Current conflict with core ANE inside APM

### ISSUE THREAD

**Issue by Ender22** [distriqt/ANE-Core#34]
I believe the core ane was updated yesterday and now APM cannot update or reinstall apps if you have certain ANE's due to a conflict:

CONFLICT :: fatal error : found [1] conflicting packages
CONFLICT :: com.distriqt.Core
CONFLICT :: ├── 7.0.0 required by: com.distriqt.playservices.AppSet@16.0.201
CONFLICT :: └── 6.4.8 required by: com.distriqt.Scanner@5.0.62

Are there any workarounds for this at the moment? I need the new core to support some ANEs (i.e. push notifs)

**Comment by marchbold** [comment]
Hi, 

We are in process of updating all our extensions to support the latest score build tools

If you post an issue in the extensions that are blocking you we'll prioritise them

**Comment by Ender22** [comment]
Hmm I'm not sure which ones will block me in total, I guess APM is just going to show me one at a time. Right now it says: 

CONFLICT :: fatal error : found [1] conflicting packages
CONFLICT :: com.distriqt.Core
CONFLICT :: ├── 7.0.1 required by: com.distriqt.ApplicationRater@6.3.0
CONFLICT :: └── 6.4.8 required by: com.distriqt.Share@7.3.0

In general I use the following

    <extensionID>com.distriqt.Application</extensionID>
    <extensionID>com.distriqt.CameraRollExtended</extensionID>
    <extensionID>com.distriqt.CameraUI</extensionID>
    <extensionID>com.distriqt.Core</extensionID>
    <extensionID>com.distriqt.Dialog</extensionID>
    <extensionID>com.distriqt.Flurry</extensionID>
    <extensionID>com.distriqt.MediaPlayer</extensionID>
    <extensionID>com.distriqt.NativeWebView</extensionID>
    <extensionID>com.distriqt.NetworkInfo</extensionID>
    <extensionID>com.distriqt.Notifications</extensionID>
    <extensionID>com.distriqt.PDFReader</extensionID>
    <extensionID>com.distriqt.Scanner</extensionID>
    <extensionID>com.distriqt.Share</extensionID>
    <extensionID>com.distriqt.PushNotifications</extensionID>
    <extensionID>com.distriqt.ApplicationRater</extensionID>
    
    and all of their dependencies. 
    
    If I just try to use the new core, and forget APM for the moment, is (for example) com.distriqt.Share going to work or fail since it says it needs com.distriqt.Core 6.4.8 ?
