### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by vree** [distriqt/ANE-Core#35]
I'm getting a compile error from Animate/Air SDK for iOS.

Error:
Invalid input
Error libCore.a, libGameServices.a, libInAppBilling.a are required to have a universal iOS libraries. (see attached image)

I'm using the latest version of Core, GameServices and InApp Billing ane.
AIR SDK version: 50.1.1.2 for iOS in Animate 2023 – macOS Big Sur 11.2.1

Error:
<img width="290" alt="Screen Shot 2023-02-19 at 3 07 06 PM" src="https://user-images.githubusercontent.com/7625186/219972804-60251144-1a05-4f8b-bb63-c7ab6ddf93a0.png">
ANE:
<img width="389" alt="Screen Shot 2023-02-19 at 3 12 13 PM" src="https://user-images.githubusercontent.com/7625186/219973068-39e43768-ee29-4e6b-89ad-0394d7d564a6.png">

Not sure if I'm missing something or need some additional updates?  Thanks for your assistance.

##### Logs

Device logs if relevant

**Comment by marchbold** [comment]
Hi,

We have moved all our extensions to the latest Xcode and Apple no longer supports universal libraries. 

Instead you should set your minimum os version to 11 and this will avoid this error.

Add the following to your info additions:

```xml
<key>MinimumOSVersion</key>
<string>11.0</string>
```

**Comment by vree** [comment]
Thanks for your help!
