### ISSUE TITLE
publish error

### ISSUE THREAD

**Issue by minikoyuncu** [distriqt/ANE-Core#36]
##### Environment 

- AIR SDK version: 50,2,2,3
- Device OS: android
- Device version: 
- Development IDE: Animate 2020
- Development OS:windows

![image](https://user-images.githubusercontent.com/11138742/230080777-4d230d4d-c2cd-46c5-8ec5-81677431d288.png)

##### Logs

Device logs if relevant

**Comment by marchbold** [comment]
Hi, Apologies for missing this one, we don't often check this repository. 

You should try posting in the adverts repository and we'll help you through it there.
