### ISSUE TITLE
Error: META-INF/ANE/iPhone-ARM/libCore.a are required to have universal iOS libraries.

### ISSUE THREAD

**Issue by GeneralVimes** [distriqt/ANE-Core#37]
I'm updating Distriqt ANEs in my game. Earlier I used Core v.6.4.8 and everything worked well together with AIR 50.2.2.6

So now I updated several ANEs, and received an error. By decreasing the changes made I found out that updating the Core only causes the same error.

So when I try to produce an Ad-Hoc build for iOS using Core 7.3.0 I get the error:
Error: META-INF/ANE/iPhone-ARM/libCore.a are required to have universal iOS libraries.

By looking inside into ANE I see indeed that the file META-INF/ANE/iPhone-ARM/libCore.a in Core v.6.4.8 has the size of 825kB and in Core v.7.3.0 its size is only 183kB

Also the file META-INF\ANE\iPhone-ARM\CoreNativeExtension.framework\CoreNativeExtension was decreased from 800 kB to 100kB.

Maybe this is connected with the update at 7.0.0 which is "feat(ios): remove bitcode"?

Or has something changed is a way I should connect Core to the app now?

**Comment by GeneralVimes** [comment]
It was my mistake: I did not specify the minimum iOS version, as I migrated to AIR 50; 
In the Application.xml right below
```
<iPhone> 
        <InfoAdditions><![CDATA[
``` 

I added: 
```
<key>MinimumOSVersion</key>
<string>11.0</string>
```

And everything worked!

**Comment by marchbold** [comment]
Yeah most our extensions have a minimum requirement of iOS 11 now, and some are higher (eg 12 for facebook). 

Highly recommend using apm to generate your app descriptor as it automatically adds this for you.
