### ISSUE TITLE
We added crashalytics

### ISSUE THREAD

**Issue by raresn** [distriqt/ANE-Core#38]
Hey, after adding crashalytics and updating all of our anes with apm, we can't compile anymore because of this error.
Any clue what we are doing wrong, @marchbold?

Error: META-INF/ANE/iPhone-ARM/libIDFA.a, META-INF/ANE/iPhone-ARM/libfirebasecore.a, META-INF/ANE/iPhone-ARM/libPushNotifications.a, META-INF/ANE/iPhone-ARM/libCore.a, META-INF/ANE/iPhone-ARM/libApplication.a, META-INF/ANE/iPhone-ARM/libContacts.a, META-INF/ANE/iPhone-ARM/libFirebaseDatabase.a, META-INF/ANE/iPhone-ARM/libFirebase.a, META-INF/ANE/iPhone-ARM/libFirebaseAuth.a are required to have universal iOS libraries. Please contact the ANE developer(s) to get the same.

**Comment by marchbold** [comment]
You need to set the minimum version to 11.

Add the following to your infoadditions:

```xml
<key>MinimumOSVersion</key>
<string>11.0</string>
```

**Comment by raresn** [comment]
Thank you.
