### ISSUE TITLE
Error on FB 4.7: Requested extension com.distriqt.cor could not be found.

### ISSUE THREAD

**Issue by danielkotzer** [distriqt/ANE-Core#39]
If you are reporting a bug please make sure you fill out the following information, otherwise delete this template and ask your question.

##### Expected behaviour
run the application on Flash Builder debuger

##### Actual behaviour
getting an error when ever I install the ane on my project and trying to run it on FB debugger:
"Error: Requested extension com.distriqt.cor could not be found."

##### Environment 

- AIR SDK version: 50.2.2.6
- Device OS: windows 10
- Device version: 
- Development IDE: Flash Builder 4.7
- Development OS: windows 10

##### Logs

Device logs if relevant

**Comment by marchbold** [comment]
Looks like a typo? The extension id should be `com.distriqt.Core` not `com.distriqt.cor`

**Comment by danielkotzer** [comment]
this is what I have on my descriptor:
<extensions>
        <extensionID>com.distriqt.Core</extensionID>
    </extensions>
</application>

**Comment by marchbold** [comment]
Probably worth checking what you have in flash builder as well. Doesn't it modify this section automatically? 

https://docs.airnativeextensions.com/docs/tutorials/getting-started-flashbuilder4.7/

**Comment by danielkotzer** [comment]
I have it on Flash builder 
I just found the solution:
on project > properties > flex builder packaging > 
Apple ios 
and Google Android
go to Native Extensions and check package next to the ane

**Comment by marchbold** [comment]
Yep, that'll do it to... :)
