### ISSUE TITLE
 'androidx.core' includes a SWF version 44, root SWF of this application: 39

### ISSUE THREAD

**Issue by dmunsie** [distriqt/ANE-Core#40]
I just subscribed to the application extension, tried creating an apk (with all included dependencies). Build was halted with this error message:

Included native extension 'androidx.core' includes a SWF version 44 which is greater than the version of the root SWF of this application: 39

APK setup creation FAILED.

I'm using FlashDevelop, Flex4+AirSDK50.2.

Everything was working fine with older versions of the extensions. Problem just now showed up after installing the latest versions.

**Comment by marchbold** [comment]
Please update your AIR version and ensure you aren't specifying an old swf version in your build process.

**Comment by dmunsie** [comment]
It's  been a while since I've updated FlashDevelop, I forgot about needed to update the XML files in the settings files. Long story short, all is working now. Thanks for the reminder. :)

**Comment by marchbold** [comment]
Great to hear! :)
