### ISSUE TITLE
Error at compilation after migrating ANEs

### ISSUE THREAD

**Issue by Nisaba** [distriqt/ANE-Core#41]
Hi,

Not sure it's the right place here to post this issue...

I've updated my Android App using many Distriqt anes.

For each ones, I get packages with APM command and copy files into my project ANEs directory.

Now, when I compile the app, I grt this error :

OTE: Multiple Android build-tools folders exist, choosing the latest version (33.0.2) for packaging
unexpected failure: Unable to run java: com.adobe.air.ADTException: gradle tool failed: 
FAILURE: Build failed with an exception.

```
* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.android.gms.internal.gtm.zzsg found in modules jetified-play-services-analytics-ics-impl-18.0.1.jar) and jetified-play-services-tagmanager-v4-impl-18.0.3 (play-services-tagmanager-v4-impl-18.0.3
     Duplicate class com.google.android.gms.internal.gtm.zzsh found in modules jetified-play-services-analytics-ics-impl-18.0.1.jar) and jetified-play-services-tagmanager-v4-impl-18.0.3 (play-services-tagmanager-v4-impl-18.0.3
     Duplicate class com.google.android.gms.internal.gtm.zzsi found in modules jetified-play-services-analytics-ics-impl-18.0.1.jar) and jetified-play-services-tagmanager-v4-impl-18.0.3 (play-services-tagmanager-v4-impl-18.0.3
```
Here are the ANEs in my Project:

- Compass
- Dialog
- Gyroscope
- Firebase
- firebase.Crashlytics
- Share
- Scanner
- NativeMaps
- Location
- NetworkInfo
- ApplicationRater
- Adverts
- IronSource
- Notifications

I noticed that in some packages, some dependency files are not at the same level.

For instance, in IronSource package, com.distriqt.playservices.Base.ane date is  20-jan-2023
Whereas com.distriqt.playservices.Base.ane date is 04-oct-2023 in Adverts package

and so on...

Possible reason for this issue ?

Thank you

**Comment by marchbold** [comment]
You should use apm to resolve the differences between the versions. Are you installing all of the extensions into your dummy project?

**Comment by Nisaba** [comment]
I've used apm in distinct dummy projects for every extension. Then, I copied the files, keeping the most recent every time.
Wrong way ?

**Comment by marchbold** [comment]
Hi, I would suggest combining them all into one project and install all the extensions you are using so apm can resolve the dependencies for you.

**Comment by Nisaba** [comment]
Hi,

That's what I've done but the same error remains.

I noticed that com.distriqt.playservices.Analytics.ane is the only ane not present in the dummy project ane, related to the anes of my project...

**Comment by marchbold** [comment]
Can you send me the project.apm and lock files and I'll see if I can replicate this behaviour.

**Comment by Nisaba** [comment]
Here is the zip in attachment
[APM.zip](https://github.com/distriqt/ANE-Core/files/14782125/APM.zip)

**Comment by marchbold** [comment]
Why are you including com.distriqt.playservices.Analytics in your app? Looks as though you are using an outdated version which could result in this conflict. 

Either remove it, update it or use apm to manage it as well:

```
apm install com.distriqt.playservices.Analytics
```

**Comment by Nisaba** [comment]
Yes,
It was an extension used by Flurry, but since Flurry is down now, I've removed this extension.
And so playservices.Analytics must be removed also.
thank you !
