### ISSUE TITLE
In NFC plugin example scene, I don't get tag id in iOS

### ISSUE THREAD

**Issue by charan-vendra** [distriqt/ANE-Core#43]
In the example scene, the tag id is not getting printed. Please help. I am using iPhone 13 pro max.
 
 I am using this version of the plugin:
 https://drive.google.com/file/d/1j_iVJj-ls4M_LfCYcz1xzZaHPHgBlnEI/view

**Comment by marchbold** [comment]
Please contact our support at unityplugins@distriqt.com
