### ISSUE TITLE
Share.ane incompatible with AIR 20 and 21

### ISSUE THREAD

**Issue by LarsLaborious** [distriqt/ANE-Core#5]
When exporting an ipa, which includes the share.ane, from Flash CC, I get this error:

`Error creating files. Undefined symbols for architecture arm64: "_kCGImagePropertyDelayTime", referenced from: -[TTOpenInppActivity localFilURLForImage:] in C:...` _here is a local path to a Temp folder_ `...libcom.distriqt.Share.a(TTOpenInAppActivity.o)...`

I'm using the latest share.ane, Flash CC, on a PC with Windows 10, 64 bit. The error sometimes refers to "armv7" instead of "arm64".

**Comment by marchbold** [comment]
Hi,

You'll have to link against a version of the iOS SDK. The AIR SDK doesn't include some parts required by our ANEs.

Have a look here as to how to do this:

http://airnativeextensions.com/knowledgebase/tutorial/1#ios

Cheers

**Comment by LarsLaborious** [comment]
So in short, I need a Mac to use it?

**Comment by LarsLaborious** [comment]
Sorry, I asked that before reading thoroughly. One short question though, is this updated http://resources.airnativeextensions.com/ios or should I find a Mac / OSX virtual machine?

**Comment by marchbold** [comment]
Yes you should find the 9.1 SDK should be appropriate. We update that whenever a new release is required for our ANEs.

Cheers

**Comment by LarsLaborious** [comment]
Thanks!

**Comment by marchbold** [comment]
No problems,
Let me know if you have any issues with the platform sdk option.
