### ISSUE TITLE
Conflict with other 3rd party extensions?

### ISSUE THREAD

**Issue by SeanJD** [distriqt/ANE-Core#6]
I'm trying to use several Distriqt extensions alongside a couple from other suppliers and have run into a potential conflict between the GoViral ane from MilkmanGames and the com.distriqt.Core ane.
It's only happening on iOS but when trying to use the facebook authentication (single sign on) feature of their extension it doesn't return to my app after facebook has authenticated.

I heard this may be due to a conflict with the Core ane stopping/intercepting inter-app messages between my app and others and tried disabling the Distriqt features and call to Core.init() and the fb authentication worked as expected.

I'm also using the Bolts ane and had read this issue https://github.com/distriqt/ANE-Parse/issues/11 which seems similar, but in my case updating to the latest version of Bolts hasn't fixed my problem (whereas disabling the Distriqt extensions does so I'm assuming it's a conflict)

Could you provide any more info on what's happening and whether there's a fix/hack to get allow this extension to work alongside others which may want access to that inter-app thread (if that's what's happening?) 

Thanks

**Comment by marchbold** [comment]
Unfortunately this is the reason the Core ANE exists. It separates out code that causes conflicts with core level application delegate overrides on iOS. 

These delegate overrides currently can only be performed by one ANE, so if you have multiple ANE's requiring these functionalities then they will conflict and the last one loaded will be the only one working.

We hope other developers would start using this method, we have made information to use this method available to anyone. However we can't control their development methods. 

Regards
