### ISSUE TITLE
iBeacon ANE issue

### ISSUE THREAD

**Issue by famousfish** [distriqt/ANE-Core#7]
I'm encountering an issue with the iBeacon ANE. 
Indeed, I use your demo code in a simple app for monitoring a region with numerous estimote devices. The code works well BUT if i disable/enable bluetooth several times in android menu, the device (the entire android system) can't detect anymore any bluetooth signal.

The only way to get back a normal running is to empty the app data cache in bluetooth system.

So, at this point, I can't use your ANE in a professional project. We can't ask app users to empty data cache manually.
Do you know this problem ? Please, could you have a look about this ?

I used these devices :
- Galaxy Tab 4 10.1 (Android 5.0.2)
- Galaxy Tab A 9.7 (Android 5.0.2)
- Asus ZenPad10 (Android 5.0.2)

**Comment by marchbold** [comment]
Hi,

Can you explain a little more what you are doing to cause the issue? How do you "disable/enable bluetooth", is it through the extension?

**Comment by famousfish** [comment]
Finally, this issue happens even if i let the app running (without disable/enable bluetooth process).

Here is my process : I made a simple app for monitoring a region (with 5 iBeacons from Estimote) pretty near for testing. I let this app running (i can see a lot of beacon update events, all is normal) but after around 15 - 20 minutes, the app detect an "exit region", then the device can't detect any bluetooth signal anymore.

It seems the app data cache of bluetooth system app is corrupted.
Thx

**Comment by marchbold** [comment]
So you don't need to switch BT on and off, simply let it run for 15-20 minutes? 

Are you doing anything in your code on the update events?

**Comment by famousfish** [comment]
Yes, I simply let it run for 15-20 minutes.
With the update events, I am only watching for beaconObjects in a loop to detect major and minor id.

for each (var beacon:BeaconObject in event.beacons)
      trace(event.region.uuid + beacon.major + beacon.minor);

**Comment by distriqt-developer** [comment]
I'm going to move this issue to the Beacon issue tracker. As it's unrelated to this ANE.

https://github.com/distriqt/ANE-Beacon/issues/33
